\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{tokyonight}[2017/08/01 Minimal modern thesis class]
 
\RequirePackage[usenames,dvipsnames]{xcolor}

% #f7768e 	This keyword, HTML elements, Regex group symbol, CSS units, Terminal Red
\definecolor{terminal_red}{HTML}{F7768E}
 
% #ff9e64 	Number and Boolean constants, Language support constants
\definecolor{orange}{HTML}{FF9E54}
 
% #e0af68 	Function parameters, Regex character sets, Terminal Yellow
\definecolor{terminal_yellow}{HTML}{E0AF68}
 
% #9ece6a 	Strings, CSS class names
\definecolor{lime}{HTML}{9ECE6A}
 
% #73daca 	Object literal keys, Markdown links, Terminal Green
% #b4f9f8 	Regex literal strings
% #2ac3de 	Language support functions, CSS HTML elements
% #7dcfff 	Object properties, Regex quantifiers and flags, Markdown headings, Terminal Cyan, Markdown code, Import/export keywords
% #7aa2f7 	Function names, CSS property names, Terminal Blue
% #bb9af7 	Control Keywords, Storage Types, Regex symbols and operators, HTML Attributes, Terminal Magenta
% #c0caf5 	Variables, Class names, Terminal White
% #a9b1d6 	Editor Foreground
% #9aa5ce 	Markdown Text, HTML Text
% #cfc9c2 	Parameters inside functions (semantic highlighting only)
% #565f89 	Comments
% #414868 	Terminal Black
% #24283b 	Editor Background (Storm)
% #1a1b26 	Editor Background (Night)
